"""Initial migration

Revision ID: 4f4ef0daa980
Revises: 
Create Date: 2025-06-24 20:56:28.466752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4ef0daa980'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=True),
    sa.Column('headsign', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=32), nullable=False),
    sa.Column('arrival_time', sa.String(length=8), nullable=True),
    sa.Column('departure_time', sa.String(length=8), nullable=True),
    sa.Column('stop_id', sa.String(length=32), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_times')
    op.drop_table('trips')
    op.drop_table('routes')
    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('regions')
    # ### end Alembic commands ###
